version: "3.3"
services:
  mysqldb:
    image: mysql:5.7.44
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_ALLOW_PUBLIC_KEY_RETRIEVAL="false"
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./mysql.cnf:/etc/mysql/my.cnf
      - ./db/dump-dbmercados-202407201948.sql:/docker-entrypoint-initdb.d/backup.sql
    expose:
      - '3306'
    container_name: mysql-local
    hostname: mysql-server-islas
    networks:
      - mercadosnetislas
  app:
    depends_on:
      - mysqldb
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    ports:
      - 8080:8080
    restart: on-failure
    env_file: ./.env
    stdin_open: true
    tty: true
    networks:
      - mercadosnetislas

networks:
  mercadosnetislas:
    driver: bridge

volumes:
  db: