version: "3.3"
services:
  postgresdb:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    expose:
      - '5432'
    container_name: postgres-local-islas
    networks:
      - mercadosnetislas

  app:
    depends_on:
      - postgresdb
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    ports:
      - 8080:8080
    restart: on-failure
    env_file: ./.env
    stdin_open: true
    tty: true
    networks:
      - mercadosnetislas

networks:
  mercadosnetislas:
    driver: bridge

volumes:
  postgres_data:
